version: "3.9"
services:
  user-service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8001:8001"

  course-service:
    build: ./course_service
    container_name: course_service
    ports:
      - "8002:8002"

  enrollment-service:
    build: ./enrollment_service
    container_name: enrollment_service
    ports:
      - "8003:8003"
    depends_on:
      - user-service
      - course-service

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
